### ISSUE TITLE
Workers not auto starting in spring boot starter

### ISSUE THREAD

**Issue by sidguptajhs** [temporalio/sdk-java#1648]
Issue in **io.temporal:temporal-spring-boot-starter-alpha:1.18.1**

## Expected Behavior
Workers should start and workflows should be processed.

## Actual Behavior

Workflows don't execute and time out. No errors in the spring logs.

## Steps to Reproduce the Problem

  1. Get a spring boot starter alpha based flow working with version 1.17.0 . Use start-workers flag
  2. Change version to 1.18.1 and restart application

## Specifications

  - Version: 1.18.1
  - Platform: amd64

## Spring Config

```
spring.temporal:
  start-workers: true
  workers:
    - task-queue: z_res_proc_int
      capacity:
        max-concurrent-workflow-task-executors: 10
        max-concurrent-activity-executors: 20
        max-concurrent-local-activity-executors: 2
        max-concurrent-workflow-task-pollers: 3
        max-concurrent-activity-task-pollers: 3
      rate-limits:
        max-worker-activities-per-second: 5.0
        max-task-queue-activities-per-second: 5.0
    - task-queue: z_hc_exec
      capacity:
        max-concurrent-workflow-task-executors: 20
        max-concurrent-activity-executors: 50
        max-concurrent-local-activity-executors: 5
        max-concurrent-workflow-task-pollers: 3
        max-concurrent-activity-task-pollers: 3
      rate-limits:
        max-worker-activities-per-second: 5.0
        max-task-queue-activities-per-second: 5.0
    - task-queue: z_infra_ops
      capacity:
        max-concurrent-workflow-task-executors: 5
        max-concurrent-activity-executors: 1
        max-concurrent-local-activity-executors: 1
        max-concurrent-workflow-task-pollers: 1
        max-concurrent-activity-task-pollers: 1
      rate-limits:
        max-worker-activities-per-second: 5.0
        max-task-queue-activities-per-second: 5.0
  workflow-cache:
      max-instances: 10
      max-threads: 10
  connection:
    target: local
  workers-auto-discovery:
    packages:
      - com.sample
```
