### ISSUE TITLE
metric not exposed without workersAutoDiscovery property when using spring boot actuator.

### ISSUE THREAD

**Issue by GwiYeong** [temporalio/sdk-java#2287]
## Expected Behavior
I'm using temporal spring boot `io.temporal:temporal-spring-boot-starter:1.25.1` and try to scrape metric from the temporal client.
I have two application, one is worker and other is api. Worker application was successfully showing metric(I can get metric from `http://localhost:8080/metrics/prometheus` but api application could not. After I'm trying to resolve this problem, finally I found one thing.
This is my api application properties
```
spring:
  temporal:
    namespace: local
    connection:
      target: 127.0.0.1:7233
```
There is no `workersAutoDiscovery` property that the worker has, because api doesn't need to start the worker, only use workflowClient, so I didn't put the property.
After putting the `workersAutoDiscovery` as dummy, the api application is showing metric (still worker is not started because package is dummy)
```
spring:
  temporal:
    namespace: local
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages: dummy
```
## Actual Behavior
Shows the temporal metric to the actuator without the `workersAutoDiscovery` property.

## Steps to Reproduce the Problem

  1. As written above.

## Specifications

  - Version: io.temporal:temporal-spring-boot-starter:1.25.1
  - Platform: Java 18
